Now that we're generating hyper-parameters from a distribution, we can sample paths from it. 

Here we are just looking at the mu's (not the y's):

```{r,error=FALSE, warning=FALSE, results='hide', message=FALSE, echo=FALSE}
# Some code that looks into whether our fake data generation is working right:

require(plyr)
require(ggplot2)

setwd(Sys.getenv("GITHUB_PATH"))
setwd("./misc/stan models/increasing by chi square increments/")
source("data generation function.R")

set.seed(38738)
samples <- ldply(1:20, function(x) {
  fake_data <- generate_data_including_hyperparameters(50)
  fake_data$sample_number <- x
  fake_data
})
ggplot() + geom_line(data=samples, mapping=aes(x=t,y=mu, color="mu", group=sample_number))
```
                     

Now we'll plot a few examples of mu's and y's:

```{r,error=FALSE, warning=FALSE, results='hide', message=FALSE, echo=FALSE}
plot_fake_data <- function(fake_data) {
  fake_data_plot <- ggplot() + scale_color_discrete("") +
    geom_line(data=fake_data, mapping=aes(x=t,y=mu, color="mu")) +
    geom_point(data=fake_data, mapping=aes(x=t,y=y,color="y")) 
  print(fake_data_plot)
}

for (i in 1:4) {
  plot_fake_data(generate_data_including_hyperparameters(20))
}

fake_data <- generate_data_mean_var(10, 10, 200, 1)
```


Confirm that our function for drawing data from a distribution with specified mean/variance for mu_N actually has that mean/variance:


```{r}

mean_mu_N = 10
sigma_mu_N_sq = 10
N = 20
sigma_0_sq = 1 

samples <- sapply(1:1000, function(x) generate_data_mean_var(mean_mu_N, sigma_mu_N_sq, N, sigma_0_sq)$mu[N])
mean(samples)
var(samples)

mean_mu_N <- 20
samples <- sapply(1:1000, function(x) generate_data_mean_var(mean_mu_N, sigma_mu_N_sq, N, sigma_0_sq)$mu[N])
mean(samples)
var(samples)
```