```{r libs,error=FALSE, warning=FALSE, results='hide', message=FALSE, echo=FALSE}
require(plyr)
require(ggplot2)
library(rstan)
library(reshape2)
setwd(Sys.getenv("GITHUB_PATH"))
setwd("./misc/stan models/increasing by chi square increments/")
source("data generation function.R")
source("chi_square_jumps_hierarchical.R")
```

More samples and fits!

```{r fit_many_models, fig.show='hide', cache=TRUE,error=FALSE, warning=FALSE, results='hide', message=FALSE, echo=FALSE}
set.seed(657465)
fits <- list()
# fits[[length(fits)+1]] <- c(fits,generate_data_and_fit_both_models(50,10))
# fits[[length(fits)+1]] <- c(fits,generate_data_and_fit_both_models(50,10))
# fits[[length(fits)+1]] <- c(fits,generate_data_and_fit_both_models(50,10))
# fits[[length(fits)+1]] <- c(fits,generate_data_and_fit_both_models(50,10))
# fits[[length(fits)+1]] <- c(fits,generate_data_and_fit_both_models(50,5))
# fits[[length(fits)+1]] <- c(fits,generate_data_and_fit_both_models(20,10))
fits[[length(fits)+1]] <- c(fits,generate_data_and_fit_both_models(15,5))
fits[[length(fits)+1]] <- c(fits,generate_data_and_fit_both_models(10,5))
```

Plot the data with the model fit:

```{r display_many_fits, dependson="fit_many_models",error=FALSE, warning=FALSE, message=FALSE, echo=FALSE}
for (fit in fits) {
  print(fit$fit)
  print(fit$plot + ggtitle("data and model, aggregated and not"))
  
  
  print(plot_samples(fit, 20))
  
  fits1 <- fit
 fake_data <- fits1$fake_data
fit <- fits1$fit
fit_aggregated <- fits1$fit_aggregated
par <- c("mu_N", "sigma_N")
truth <- fake_data[1,par]  #global for silly reasons
truth
true_ratio <- as.numeric(truth[2]/truth[1])
s <- extract(fit, pars=par)
posterior_ratio <- sapply(1:length(s$sigma_N), function(i) s$sigma_N[i]/s$mu_N[i])
s <- extract(fit_aggregated, pars=par)
posterior_ratio_aggregated <- sapply(1:length(s$sigma_N), function(i) s$sigma_N[i]/s$mu_N[i])
samplesDF <- rbind(data.frame(par=posterior_ratio, model="not aggregated"),
                     data.frame(par=posterior_ratio_aggregated, model="aggregated"))
  print(
    ggplot(data=samplesDF) + 
      geom_histogram(mapping=aes(par, ..density..), alpha=.5,position="dodge") +
      geom_vline(aes(xintercept = true_ratio)) + facet_grid(model ~ ., scales="free_y") +
      ggtitle(paste("posterior for sigma_N/mu_N with line at truth"))
  )
 

}
```